name: party
description: Party mobile client.

dependencies:
  spotify:
    git:
      url: git://github.com/chances/spotify-dart.git
      ref: party
  fluro: ^1.1.0
  shared_preferences: ^0.4.0
  flutter_search_bar:
    git:
      url: git://github.com/ArcticZeroo/flutter-search-bar.git
      ref: master
  flutter_webview_plugin:
    git:
      url: git://github.com/chances/flutter_webview_plugin.git
      ref: master
  json_annotation: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
#  flutter_test: any
#    sdk: flutter
  build_runner: ^0.8.10
  json_serializable: ^0.5.0

# json_serializer JSON model generation:
# $ flutter packages pub run build_runner build

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
